### ISSUE TITLE
Converting .sf2 to .wav for processing

### ISSUE THREAD

**Issue by gleitz** [PatrickWolleb/SoundFontJS#1]
Hi,

What is the best way for converting a SoundFont (.sf2) to a .wav (all the notes of a instrument in 2 second intervals. The lowest note should start at A-1 and continue 8 octaves) so that I can then run the .wav through SoundFontJS to get something that works with MIDI.js? In a nutshell how so I go from .sf2 -> MIDI.js compatible .js file?

I found [this page](http://29a.ch/2010/2/7/converting-midi2wav-using-fluidsynth) which describes turning a .mid file into .wav. Perhaps you have a .mid file that contains all the notes of a instrument in 2 second intervals?

Also, do you know of any repository of MIDI.js compatible sound files out there?

I ask because I want to expand the number of instruments used by [Symphony of Satellites](http://bit.ly/spaceharp) ([http://github.com/gleitz/spheremusic](http://github.com/gleitz/spheremusic)).

**Comment by PatrickWolleb** [comment]
Hi i think you are looking for this
https://github.com/mudcube/MIDI.js/tree/master/soundfont-generator

.

**Comment by gleitz** [comment]
Fantastic! I ended up getting the .js files created but I had to alter the script slightly. For some reason this command didn't generate a valid .wav file:

`/usr/local/bin/fluidsynth -C 1 -R 1 -g 0.5 -F ../../soundfont/A0.wav ./FluidR3_GM.sf2 ../../soundfont/temp.midi`

Instead, I created a .raw file with fluidsynth and then used sox to generate the wav:

```
/usr/local/bin/fluidsynth -C 1 -R 1 -g 0.5 -F fluidsynth.raw ./FluidR3_GM.sf2 ../../soundfont/temp.midi
/usr/local/bin/sox -b 16 -c 2 -s -r 44100 fluidsynth.raw ../../soundfont/F2.wav
```

Here's the fix: [https://github.com/gleitz/MIDI.js/commit/217bc47d8238ecfeeb535bbe1d0a37bd7d0da1bd](https://github.com/gleitz/MIDI.js/commit/217bc47d8238ecfeeb535bbe1d0a37bd7d0da1bd)

Thanks again for your help.
